# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ExecuteRequest(UniversalBaseModel):
    """
    Request to execute a command in a sandbox.
    """

    command: str = pydantic.Field()
    """
    Command or code to execute
    """

    timeout: typing.Optional[int] = pydantic.Field(default=None)
    """
    Execution timeout in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
