# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SandboxUrls(UniversalBaseModel):
    """
    URLs associated with a sandbox.
    """

    wss_url: typing.Optional[str] = None
    vnc_url: typing.Optional[str] = None
    mcp_url: typing.Optional[str] = None
    api_url: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
