# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sandbox_urls import SandboxUrls


class SandboxResponse(UniversalBaseModel):
    """
    Response containing sandbox details.
    """

    id: str
    type: str
    provider: str
    region: typing.Optional[str] = None
    status: str
    created_at: str
    expires_at: typing.Optional[str] = None
    urls: typing.Optional[SandboxUrls] = None
    timeout: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
